config/routes.rb
Rails.application.routes.draw do
  resources :school_class_masters
  root 'dashboard#index'

  resources :student_classes
  resources :student_scores
  resources :subjects
  resources :subject_masters
  resources :students

  resources :school_classes do
    resources :class_teachers, only: [:new, :create, :destroy]
    resources :student_classes, only: [:new, :create, :destroy]
    resources :students, only: [:new, :create, :destroy]
  end

  resources :subject_masters do
    resources :subjects, only: [:new, :create, :destroy]
  end

  resources :teachers

  resource :login
  get '/logout' => 'logins#destroy', as: :logout

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)









end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/class_teacher.rb
class ClassTeacher < ActiveRecord::Base
	belongs_to :teacher
	belongs_to :school_class
end

app/models/school_class.rb
class SchoolClass < ActiveRecord::Base
  has_many :class_teachers, dependent: :destroy
  has_many :teachers, through: :class_teachers

  has_many :student_classes, dependent: :destroy
  has_many :students, through: :student_classes

  has_many :school_class_subjects, dependent: :destroy
  has_many :subjects, through: :school_class_subjects

  belongs_to :school_class_master
end

app/models/school_class_master.rb
class SchoolClassMaster < ActiveRecord::Base
	has_many :school_classes
end

app/models/school_class_subject.rb
class SchoolClassSubject < ActiveRecord::Base
	belongs_to	:subject
	belongs_to	:school_classe
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :student_classes, dependent: :destroy
  has_many :school_classes, through: :student_classes

  has_many :student_scores, dependent: :destroy
  has_many :subjects, through: :student_scores

  attr_accessor :school_class_id
end

app/models/student_class.rb
class StudentClass < ActiveRecord::Base
	belongs_to :student
	belongs_to :school_class
end

app/models/student_score.rb
class StudentScore < ActiveRecord::Base
	belongs_to	:subject
	belongs_to	:student
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :student_scores, dependent: :destroy
  has_many :students, through: :student_scores

  has_many :teacher_subjects, dependent: :destroy
  has_many :teachers, through: :teacher_subjects

  has_many :school_class_subjects, dependent: :destroy
  has_many :school_classes, through: :school_class_subjects

  belongs_to :subject_master

  def name
    self.subject_master.name
  end

  def semester_to_string
    case self.semester
    when 1
      '前期'
    when 2
      '後期'
    end
  end
end

app/models/subject_master.rb
class SubjectMaster < ActiveRecord::Base
	has_many :subjects
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :class_teachers
  has_many :school_classes, through: :class_teachers
  
  has_many :teacher_subjects, dependent: :destroy
  has_many :subjects, through: :teacher_subjects

  before_save :encryption_to_password

  def authenticate password
    self.password == Digest::MD5.new.update(password).to_s
  end

  private

  def encryption_to_password
    self.password = Digest::MD5.new.update(self.password).to_s
    self
  end
end

app/models/teacher_subject.rb
class TeacherSubject < ActiveRecord::Base
	belongs_to	:subject
	belongs_to	:teacher
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @teacher = current_teacher
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  layout 'login'

  def show
    render "new"
  end

  def create
    teacher = Teacher.find_by login_id: params[:login_id]
    if teacher && teacher.authenticate(params[:password])
      session[:teacher_id] = teacher.id
      flash[:toast] = 'ログインしました'
      redirect_to root_path
    else
      flash.now.alert = "失敗しました。login_id=#{params[:login_id]}"
      render "new"
    end
  end

  def destroy
    reset_session
    flash[:toast] = 'ログアウトしました'
    redirect_to login_path
  end

  private

  def use_authenticate?
    false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/class_teachers_helper.rb
module ClassTeachersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/school_classes_helper.rb
module SchoolClassesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<% content_for :title, 'ダッシュボード' %>

<div class="row">
  <div class="col m4 s12">
    <h5><%= current_teacher.name %></h5>
    <p>
      ID:&nbsp;<%= current_teacher.login_id %><br>
      <br>
      <%= link_to edit_teacher_path(current_teacher), class: 'btn' do %>
        <%= fa_icon 'edit' %>&nbsp;ユーザ情報編集
      <% end %>
      <%= link_to logout_path, class: 'btn  red darken-2' do %>
        <%= fa_icon 'sign-out' %>&nbsp;ログアウト
      <% end %>
    </p>
  </div>
  <div class="col m4 s12">
    
  </div>
  <div class="col m4 s12">
    
  </div>
</div>

<div class="divider"></div>



<div class="row section">
  <div class="col m6 s12">
    <div class="collection z-depth-1">
      <div class="collection-item">
        <h5><%= fa_icon 'users' %>&nbsp;担当クラス</h5>
      </div>
      <% current_teacher.school_classes.each do |c| %>
        <%= link_to c, class: 'collection-item' do  %>
          <%= c.name %>
          <span class="secondary-content">
            <%= c.students.length %>&nbsp;
            <%= fa_icon 'user' %>
          </span>
        <% end %>
      <% end %>
      <%= link_to new_school_class_path, class: 'collection-item' do %>
        <%= fa_icon 'plus' %>&nbsp;担当クラスを作成
      <% end %>
    </div>
  </div>
  <div class="col m6 s12">
    <div class="collection z-depth-1">
      <div class="collection-item">
        <h5><%= fa_icon 'pencil' %>&nbsp;担当科目</h5>
      </div>
      <% current_teacher.subjects.each do |s| %>
        <%= link_to s, class: 'collection-item' do %>
          <%= s.name %>
          <span class="secondary-content">
            <%= s.students.length %>&nbsp;
            <%= fa_icon 'user' %>
          </span>
        <% end %>
      <% end %>
      <%= link_to new_subject_path, class: 'collection-item' do %>
        <%= fa_icon 'plus' %>&nbsp;担当科目を作成
      <% end %>
    </div>
  </div>
</div>
