config/routes.rb
Rails.application.routes.draw do
  resources :school_class_masters
  root 'dashboard#index'

  resources :student_classes
  resources :student_scores
  resources :subjects
  resources :subject_masters
  resources :students

  resources :school_classes do
    resources :class_teachers, only: [:new, :create, :destroy]
    resources :student_classes, only: [:new, :create, :destroy]
    resources :students, only: [:new, :create, :destroy]
  end

  resources :subject_masters do
    resources :subjects, only: [:new, :create, :destroy]
  end

  resources :teachers

  resource :login
  get '/logout' => 'logins#destroy', as: :logout

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)









end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/class_teacher.rb
class ClassTeacher < ActiveRecord::Base
	belongs_to :teacher
	belongs_to :school_class
end

app/models/school_class.rb
class SchoolClass < ActiveRecord::Base
  has_many :class_teachers, dependent: :destroy
  has_many :teachers, through: :class_teachers

  has_many :student_classes, dependent: :destroy
  has_many :students, through: :student_classes

  has_many :school_class_subjects, dependent: :destroy
  has_many :subjects, through: :school_class_subjects

  belongs_to :school_class_master
end

app/models/school_class_master.rb
class SchoolClassMaster < ActiveRecord::Base
	has_many :school_classes
end

app/models/school_class_subject.rb
class SchoolClassSubject < ActiveRecord::Base
	belongs_to	:subject
	belongs_to	:school_classe
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :student_classes, dependent: :destroy
  has_many :school_classes, through: :student_classes

  has_many :student_scores, dependent: :destroy
  has_many :subjects, through: :student_scores

  attr_accessor :school_class_id
end

app/models/student_class.rb
class StudentClass < ActiveRecord::Base
	belongs_to :student
	belongs_to :school_class
end

app/models/student_score.rb
class StudentScore < ActiveRecord::Base
	belongs_to	:subject
	belongs_to	:student
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :student_scores, dependent: :destroy
  has_many :students, through: :student_scores

  has_many :teacher_subjects, dependent: :destroy
  has_many :teachers, through: :teacher_subjects

  has_many :school_class_subjects, dependent: :destroy
  has_many :school_classes, through: :school_class_subjects

  belongs_to :subject_master

  def name
    self.subject_master.name
  end

  def semester_to_string
    case self.semester
    when 1
      '前期'
    when 2
      '後期'
    end
  end
end

app/models/subject_master.rb
class SubjectMaster < ActiveRecord::Base
	has_many :subjects
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :class_teachers
  has_many :school_classes, through: :class_teachers
  
  has_many :teacher_subjects, dependent: :destroy
  has_many :subjects, through: :teacher_subjects

  before_save :encryption_to_password

  def authenticate password
    self.password == Digest::MD5.new.update(password).to_s
  end

  private

  def encryption_to_password
    self.password = Digest::MD5.new.update(self.password).to_s
    self
  end
end

app/models/teacher_subject.rb
class TeacherSubject < ActiveRecord::Base
	belongs_to	:subject
	belongs_to	:teacher
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  layout 'login'

  def show
    render "new"
  end

  def create
    teacher = Teacher.find_by login_id: params[:login_id]
    if teacher && teacher.authenticate(params[:password])
      session[:teacher_id] = teacher.id
      flash[:toast] = 'ログインしました'
      redirect_to root_path
    else
      flash.now.alert = "失敗しました。login_id=#{params[:login_id]}"
      render "new"
    end
  end

  def destroy
    reset_session
    flash[:toast] = 'ログアウトしました'
    redirect_to login_path
  end

  private

  def use_authenticate?
    false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/class_teachers_helper.rb
module ClassTeachersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_flash_message.html.erb
<% if flash[:notice] || flash[:alert] %>
  <div class="card-panel">
    <b class="blue-text"><%= flash[:notice] %></b>
    <b class="red-text"><%= flash[:alert] %></b>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="page-footer teal">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">成績管理システム</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">管理ログイン</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">ヘルプ</a></li>
        </ul>
      </div>
      <div class="col l4 offset-l2 s12 right-align">
        <a href="#top" class="scroll-link btn-floating btn-large waves-effect waves-light deep-orange" style="margin-top: -60px;" title="ページトップへ"><%= fa_icon 'angle-up' %></a>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container center-align">
      &copy; 2015 Odd Team
    </div>
  </div>
</footer>

app/views/shared/_nav.html.erb
<header class="navbar-fixed" id="top">
  <nav class="teal">
    <div class="nav-wrapper">
    <a href="#top" class="brand-logo center scroll-link">成績管理システム</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a class="dropdown-button" href="#!" data-activates="classes">担当クラス<i class="mdi-navigation-arrow-drop-down right"></i></a></li>
        <li><a class="dropdown-button" href="#!" data-activates="subjects">担当科目<i class="mdi-navigation-arrow-drop-down right"></i></a></li>
        <li><%= link_to fa_icon("home"), root_path, title: 'HOME' %></li>
        <li><%= link_to fa_icon("sign-out"), logout_path, title: 'ログアウト' %></li>
      </ul>

      <ul id="slide-out" class="side-nav">
        <li><%= link_to 'HOME', root_path %></li>
        <li><%= link_to 'クラス一覧', school_classes_path %></li>
        <li><%= link_to '教員一覧', teachers_path %></li>
        <li><%= link_to '生徒一覧', students_path %></li>
        <li><%= link_to '科目マスター', subject_masters_path %></li>
        <li><%= link_to '科目一覧', subjects_path %></li>
        <hr>
        <li><%= link_to "ログアウト", logout_path, title: 'ログアウト' %></li>
      </ul>
      <a href="#" data-activates="slide-out" class="button-collapse show-on-large"><i class="mdi-navigation-menu"></i></a>
    </div>
  </nav>
</header>

<!-- Dropdown Structure -->
<ul id="classes" class="dropdown-content">
  <% current_teacher.school_classes.each do |school_class| %>
    <li><%= link_to school_class.name, school_class %></li>
  <% end %>
  <li class="divider"></li>
  <li><%= link_to '担当クラス作成', new_school_class_path %></li>
</ul>

<!-- Dropdown Structure -->
<ul id="subjects" class="dropdown-content">
  <% current_teacher.subjects.each do |subject| %>
    <li><%= link_to subject.name, subject %></li>
  <% end %>
  <li class="divider"></li>
  <li><%= link_to '担当科目作成', new_subject_path %></li>
</ul>