config/routes.rb
Rails.application.routes.draw do
  resources :school_class_masters
  root 'dashboard#index'

  resources :student_classes
  resources :student_scores
  resources :subjects
  resources :subject_masters
  resources :students

  resources :school_classes do
    resources :class_teachers, only: [:new, :create, :destroy]
    resources :student_classes, only: [:new, :create, :destroy]
    resources :students, only: [:new, :create, :destroy]
  end

  resources :subject_masters do
    resources :subjects, only: [:new, :create, :destroy]
  end

  resources :teachers

  resource :login
  get '/logout' => 'logins#destroy', as: :logout

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)









end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/class_teacher.rb
class ClassTeacher < ActiveRecord::Base
	belongs_to :teacher
	belongs_to :school_class
end

app/models/school_class.rb
class SchoolClass < ActiveRecord::Base
  has_many :class_teachers, dependent: :destroy
  has_many :teachers, through: :class_teachers

  has_many :student_classes, dependent: :destroy
  has_many :students, through: :student_classes

  has_many :school_class_subjects, dependent: :destroy
  has_many :subjects, through: :school_class_subjects

  belongs_to :school_class_master
end

app/models/school_class_master.rb
class SchoolClassMaster < ActiveRecord::Base
	has_many :school_classes
end

app/models/school_class_subject.rb
class SchoolClassSubject < ActiveRecord::Base
	belongs_to	:subject
	belongs_to	:school_classe
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :student_classes, dependent: :destroy
  has_many :school_classes, through: :student_classes

  has_many :student_scores, dependent: :destroy
  has_many :subjects, through: :student_scores

  attr_accessor :school_class_id
end

app/models/student_class.rb
class StudentClass < ActiveRecord::Base
	belongs_to :student
	belongs_to :school_class
end

app/models/student_score.rb
class StudentScore < ActiveRecord::Base
	belongs_to	:subject
	belongs_to	:student
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :student_scores, dependent: :destroy
  has_many :students, through: :student_scores

  has_many :teacher_subjects, dependent: :destroy
  has_many :teachers, through: :teacher_subjects

  has_many :school_class_subjects, dependent: :destroy
  has_many :school_classes, through: :school_class_subjects

  belongs_to :subject_master

  def name
    self.subject_master.name
  end

  def semester_to_string
    case self.semester
    when 1
      '前期'
    when 2
      '後期'
    end
  end
end

app/models/subject_master.rb
class SubjectMaster < ActiveRecord::Base
	has_many :subjects
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :class_teachers
  has_many :school_classes, through: :class_teachers
  
  has_many :teacher_subjects, dependent: :destroy
  has_many :subjects, through: :teacher_subjects

  before_save :encryption_to_password

  def authenticate password
    self.password == Digest::MD5.new.update(password).to_s
  end

  private

  def encryption_to_password
    self.password = Digest::MD5.new.update(self.password).to_s
    self
  end
end

app/models/teacher_subject.rb
class TeacherSubject < ActiveRecord::Base
	belongs_to	:subject
	belongs_to	:teacher
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  layout 'login'

  def show
    render "new"
  end

  def create
    teacher = Teacher.find_by login_id: params[:login_id]
    if teacher && teacher.authenticate(params[:password])
      session[:teacher_id] = teacher.id
      flash[:toast] = 'ログインしました'
      redirect_to root_path
    else
      flash.now.alert = "失敗しました。login_id=#{params[:login_id]}"
      render "new"
    end
  end

  def destroy
    reset_session
    flash[:toast] = 'ログアウトしました'
    redirect_to login_path
  end

  private

  def use_authenticate?
    false
  end
end

app/controllers/subject_masters_controller.rb
class SubjectMastersController < InheritedResources::Base

  private

    def subject_master_params
      params.require(:subject_master).permit(:name, :credit, :time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/class_teachers_helper.rb
module ClassTeachersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/school_classes_helper.rb
module SchoolClassesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subject_masters_helper.rb
module SubjectMastersHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/subject_masters/_form.html.erb
<%= form_for(@subject_master) do |f| %>
  <% if @subject_master.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject_master.errors.count, "error") %> prohibited this subject_master from being saved:</h2>

      <ul>
      <% @subject_master.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :credit %><br>
    <%= f.number_field :credit %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.number_field :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subject_masters/edit.html.erb
<h1>Editing Subject Master</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject_master %> |
<%= link_to 'Back', subject_masters_path %>

app/views/subject_masters/index.html.erb
<% content_for :title, '科目マスター一覧' %>

<h1>Listing Subject Masters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Credit</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subject_masters.each do |subject_master| %>
      <tr>
        <td><%= subject_master.name %></td>
        <td><%= subject_master.credit %></td>
        <td><%= subject_master.time %></td>
        <td><%= link_to 'Show', subject_master %></td>
        <td><%= link_to 'Edit', edit_subject_master_path(subject_master) %></td>
        <td><%= link_to 'Destroy', subject_master, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject master', new_subject_master_path %>

app/views/subject_masters/new.html.erb
<h1>New Subject Master</h1>

<%= render 'form' %>

<%= link_to 'Back', subject_masters_path %>

app/views/subject_masters/show.html.erb
<% content_for :title, '科目マスター情報' %>

<p>
  <strong>Name:</strong>
  <%= @subject_master.name %>
</p>

<p>
  <strong>Credit:</strong>
  <%= @subject_master.credit %>
</p>

<p>
  <strong>Time:</strong>
  <%= @subject_master.time %>
</p>

<%= link_to 'Edit', edit_subject_master_path(@subject_master) %> |
<%= link_to 'Back', subject_masters_path %>