config/routes.rb
Rails.application.routes.draw do
  resources :school_class_masters
  root 'dashboard#index'

  resources :student_classes
  resources :student_scores
  resources :subjects
  resources :subject_masters
  resources :students

  resources :school_classes do
    resources :class_teachers, only: [:new, :create, :destroy]
    resources :student_classes, only: [:new, :create, :destroy]
    resources :students, only: [:new, :create, :destroy]
  end

  resources :subject_masters do
    resources :subjects, only: [:new, :create, :destroy]
  end

  resources :teachers

  resource :login
  get '/logout' => 'logins#destroy', as: :logout

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)









end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/class_teacher.rb
class ClassTeacher < ActiveRecord::Base
	belongs_to :teacher
	belongs_to :school_class
end

app/models/school_class.rb
class SchoolClass < ActiveRecord::Base
  has_many :class_teachers, dependent: :destroy
  has_many :teachers, through: :class_teachers

  has_many :student_classes, dependent: :destroy
  has_many :students, through: :student_classes

  has_many :school_class_subjects, dependent: :destroy
  has_many :subjects, through: :school_class_subjects

  belongs_to :school_class_master
end

app/models/school_class_master.rb
class SchoolClassMaster < ActiveRecord::Base
	has_many :school_classes
end

app/models/school_class_subject.rb
class SchoolClassSubject < ActiveRecord::Base
	belongs_to	:subject
	belongs_to	:school_classe
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :student_classes, dependent: :destroy
  has_many :school_classes, through: :student_classes

  has_many :student_scores, dependent: :destroy
  has_many :subjects, through: :student_scores

  attr_accessor :school_class_id
end

app/models/student_class.rb
class StudentClass < ActiveRecord::Base
	belongs_to :student
	belongs_to :school_class
end

app/models/student_score.rb
class StudentScore < ActiveRecord::Base
	belongs_to	:subject
	belongs_to	:student
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :student_scores, dependent: :destroy
  has_many :students, through: :student_scores

  has_many :teacher_subjects, dependent: :destroy
  has_many :teachers, through: :teacher_subjects

  has_many :school_class_subjects, dependent: :destroy
  has_many :school_classes, through: :school_class_subjects

  belongs_to :subject_master

  def name
    self.subject_master.name
  end

  def semester_to_string
    case self.semester
    when 1
      '前期'
    when 2
      '後期'
    end
  end
end

app/models/subject_master.rb
class SubjectMaster < ActiveRecord::Base
	has_many :subjects
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :class_teachers
  has_many :school_classes, through: :class_teachers
  
  has_many :teacher_subjects, dependent: :destroy
  has_many :subjects, through: :teacher_subjects

  before_save :encryption_to_password

  def authenticate password
    self.password == Digest::MD5.new.update(password).to_s
  end

  private

  def encryption_to_password
    self.password = Digest::MD5.new.update(self.password).to_s
    self
  end
end

app/models/teacher_subject.rb
class TeacherSubject < ActiveRecord::Base
	belongs_to	:subject
	belongs_to	:teacher
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  layout 'login'

  def show
    render "new"
  end

  def create
    teacher = Teacher.find_by login_id: params[:login_id]
    if teacher && teacher.authenticate(params[:password])
      session[:teacher_id] = teacher.id
      flash[:toast] = 'ログインしました'
      redirect_to root_path
    else
      flash.now.alert = "失敗しました。login_id=#{params[:login_id]}"
      render "new"
    end
  end

  def destroy
    reset_session
    flash[:toast] = 'ログアウトしました'
    redirect_to login_path
  end

  private

  def use_authenticate?
    false
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]
  before_action :set_subject_masters, only: [:new, :edit, :update]

  def index
    @q        = Subject.search(search_params)
    @subjects = @q.result(distinct: true)
  end

  def show
  end

  def new
    # @subject = Subject.new
    if params[:subject_master_id]
      @subject = Subject.new
      @subject_master = SubjectMaster.find(params[:subject_master_id])
    else
      @q               = SubjectMaster.search(search_params)
      @subject_masters = @q.result(distinct: true)
    end
  end

  def create
    @subject = Subject.new(subject_params)

    if @subject.save
      teacher_subject = current_teacher.teacher_subjects.build do |ts|
        ts.subject_id = @subject.id
      end
      teacher_subject.save
      redirect_to @subject, notice: '作成しました'
    else
      render :new
    end
  end

  def edit
  end

  def destroy
  end

  private

  def set_subject
    @subject = Subject.find(params[:id])
  end

  def set_subject_masters
    @subject_masters = SubjectMaster.all
  end

  def subject_params
    params.require(:subject).permit(:subject_type, :year, :semester, :subject_master_id)
  end

  def search_params
    params.require(:q).permit(
      :s,
      :subject_master_name_cont,
      :semester_eq,
      :year_eq,
      :subject_type_eq,

      :name_cont
    )
  rescue
    nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/class_teachers_helper.rb
module ClassTeachersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/school_classes_helper.rb
module SchoolClassesHelper
end

app/helpers/student_scores_helper.rb
module StudentScoresHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= f.label :履修 %><br>
    <%= f.radio_button :subject_type, '必修', id: 'radio-1', checked: true %><%= f.label "必修", for: 'radio-1' %><br>
    <%= f.radio_button :subject_type, '選択', id: 'radio-2' %><%= f.label "選択", for: 'radio-2' %><br><br>
  </div>
  <div class="input-field">
    <%= f.label :履修年度 %><br>
    <% years = (1946..(Time.now.year+5)).to_a %>
    <% ryears= years.reverse %>
    <%= f.select :year, ryears.map{|a| [a, a] }, {:include_blank => '選択してください'} %>
  </div>
  <div class="input-field">
    <%= f.label :学期 %><br>
    <!-- %= f.number_field :semester %-->
    <%= f.radio_button :semester, 1, id: 'radio-3', checked: true %><%= f.label "前期", for: 'radio-3' %><br>
    <%= f.radio_button :semester, 2, id: 'radio-4' %><%= f.label "後期", for: 'radio-4' %>
  </div><br>
  <div class="input-field">
    <%= f.label :科目 %><br>
    <!-- %= f.number_field :subject_master_id % -->
    <%= f.collection_select :subject_master_id, @subject_masters, :id, :name , {:include_blank => '選択してください'}%><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/_new_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :subject_master_id, value: @subject_master.id %>

  <div class="row">
    <div class="col s12">履修科目 (必修/選択)</div>
    <div class="input-field col s6 m6 l6">
      <%= f.select :subject_master_id, { @subject_master.name => @subject_master.id }, {}, {disabled: true}  %>
    </div>

    <div class="input-field col s6 m6 l6">
      <%= f.radio_button :subject_type, '必修', id: 'radio-1', checked: true %>
      <%= f.label "必修", for: 'radio-1' %>
      <%= f.radio_button :subject_type, '選択', id: 'radio-2' %>
      <%= f.label "選択", for: 'radio-2' %>
    </div>
  </div>

  <div class="row">
    <div class="col s12">履修年度 (西暦)</div>
    <div class="input-field col s4 m2 l2">
      <% year = Time.now.year %>
      <%= f.number_field :year, value: year, min: 1946, required: true %>
    </div>

    <div class="input-field col s8 m10 l10">
      <!-- %= f.number_field :semester %-->
      <%= f.radio_button :semester, 1, id: 'radio-3', checked: true %>
      <%= f.label "前期", for: 'radio-3' %>
      <%= f.radio_button :semester, 2, id: 'radio-4' %>
      <%= f.label "後期", for: 'radio-4' %>
    </div>
  </div>

  <div class="center-align">
    <%= f.submit '作成', class: 'btn' %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<% content_for :title, '科目一覧' %>

<%= search_form_for @q do |f| %>
  <div class="row card-panel">
    <div class="input-field col s12 m12 l5">
      <%= f.text_field :subject_master_name_cont %>
      <%= f.label :subject_master_name_cont, "科目名" %>
    </div>
    <div class="input-field col s12 m3 l2">
      <%= f.number_field :year_eq, value: Time.now.year, min: 1946 %>
      <%= f.label :year_eq, "年度" %>
    </div>
    <div class="input-field col s12 m3 l2">
      <%= f.select :semester_eq, {"学期を選択" => nil ,"前期" => 1, "後期" => 2} %>
      <%= f.label :semester_eq, "学期" %>
    </div>
    <div class="input-field col s12 m3 l2">
      <%= f.select :subject_type_eq, {"科目種別を選択" => nil ,"必修" => "必修", "選択" => "選択"} %>
      <%= f.label :subject_type_eq, "科目種別" %>
    </div>
    <div class="input-field col s12 m3 l1">
      <%= button_tag class: 'btn-floating waves-effect waves-light' do %>
        <%= fa_icon 'search' %>
      <% end %>
    </div>
  </div>
<% end %>

<table class="hoverable">
  <thead>
    <tr>
      <th>科目種別</th>
      <th><%= sort_link(@q, :year, '履修年度') %></th>
      <th>学期</th>
      <th><%= sort_link(@q, :subject_master_name, '科目名') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.subject_type %></td>
        <td><%= subject.year %></td>
        <td><%= subject.semester_to_string %></td>
        <td><%= subject.name %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to new_subject_path, class: "btn-floating btn-large tooltipped waves-effect waves-light deep-orange", data: { position: "top", tooltip: "科目作成" } do %>
  <%= fa_icon 'plus' %>
<% end %>

app/views/subjects/new.html.erb
<% content_for :title, '科目作成' %>

<% unless @subject %>
  <%= link_to '科目マスター選択', new_subject_path, class: 'black-text' %> <%= fa_icon 'arrow-right' %> <span class="grey-text text-lighten-2">科目情報入力</span>
  <div class="divider"></div>
  <h5>科目マスター選択</h5>

  <div class="collection">
    <%= search_form_for @q, url: new_subject_path, class: 'collection-item' do |f| %>
      <div class="row">
        <div class="input-field col s12 m10 l11">
          <%= f.text_field :name_cont %>
          <%= f.label :name_cont, "科目名" %>
        </div>
        <div class="input-field col s12 m2 l1">
          <%= button_tag class: 'btn-floating waves-effect waves-light' do %>
            <%= fa_icon 'search' %>
          <% end %>
        </div>
      </div>
    <% end %>

    <% @subject_masters.each do |master| %>
      <%= link_to master.name, new_subject_master_subject_path(master), class: 'collection-item' %>
    <% end %>
  </div>

<% else %>

  <%= link_to '科目マスター選択', new_subject_path, class: 'grey-text text-lighten-2' %> <%= fa_icon 'arrow-right' %> 科目情報入力
  <div class="divider"></div>

  <h5>科目情報入力</h5>
  <br>
  <%= render 'new_form' %>

<% end %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @subject.name %></h1>

<div class="row">
</div>
<p>
  <strong>Type:</strong>
  <%= @subject.subject_type %>
</p>

<p>
  <strong>Year:</strong>
  <%= @subject.year %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @subject.semester %>
</p>

<div class="row">
  <div class="col m6">
    <h5>講師</h5>
    <div class="collection">
      <% @subject.teachers.each do |teacher| %>
        <%= link_to teacher.name, teacher, class: 'collection-item' %>
      <% end %>
    </div>
  </div>
  <div class="col m6">
    <h5>生徒</h5>
    <div class="collection">
      <% @subject.students.each do |student| %>
        <%= link_to student.name, student, class: 'collection-item' %>
      <% end %>
    </div>
  </div>
</div>
<hr>
<h5>成績</h5>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>